language: php

php:
  - 7.0
  - 7.1
  - hhvm

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -yqq g++-4.8
  - export CXX="g++-4.8"

before_script:
  - composer install --prefer-source --no-interaction --dev
  - composer install-drafter
  - git config --global user.name travis-ci
  - git config --global user.email travis@example.com

script: vendor/bin/phpunit
